use_frameworks!

platform :ios, '10.0'

target 'iReadEpub_Example' do
  pod 'iReadEpub', :path => '../'

  target 'iReadEpub_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Fuzi' , '~> 3.1.3'
    pod 'DifferenceKit' , '~> 1.3.0'
    pod 'CryptoSwift', '~> 1.5.1'
  end
end
