use_frameworks!

platform :ios, '14.0'

target 'iReadEpub_Example' do
  pod 'iReadEpub', :path => '../'

  target 'iReadEpub_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
